@startuml
title User Accesses EKS Application with Google Federated Authentication using OIDC and DynamoDB session management

actor User
participant CloudFront
participant ALB
participant APIGateway
participant IngressController
participant Cognito
participant EKSService
participant GoogleOIDC
database DynamoDB

User -> CloudFront: HTTPS Request
CloudFront -> ALB: HTTPS Request
ALB -> APIGateway: HTTP Request
APIGateway -> Cognito: HTTPS Request
Cognito -> GoogleOIDC: OIDC Request
GoogleOIDC -> Cognito: OIDC Response
Cognito -> APIGateway: HTTPS Response

activate User
APIGateway -> DynamoDB: Read Token
alt Token is valid
    alt Session is valid
        DynamoDB -> IngressController: HTTP Request with Token
        deactivate User
        IngressController -> EKSService: HTTP Request with Token
        EKSService -> IngressController: HTTP Response
        activate User
        IngressController -> APIGateway: HTTP Response
        APIGateway -> ALB: HTTP Response
        ALB -> CloudFront: HTTP Response
        CloudFront -> User: HTTPS Response
    else Session is expired
        DynamoDB -> APIGateway: Delete Token
        deactivate User
        APIGateway -> Cognito: HTTPS Request
        Cognito -> GoogleOIDC: OIDC Request
        GoogleOIDC -> Cognito: OIDC Response
        Cognito -> APIGateway: HTTPS Response
        APIGateway -> CloudFront: Redirect to Login Page
        CloudFront -> User: HTTPS Response
    end
else Token is expired
    DynamoDB -> APIGateway: Delete Token
    deactivate User
    APIGateway -> Cognito: HTTPS Request
    Cognito -> GoogleOIDC: OIDC Request
    GoogleOIDC -> Cognito: OIDC Response
    Cognito -> APIGateway: HTTPS Response
    APIGateway -> DynamoDB: Write Token
    DynamoDB -->> APIGateway: OK
    APIGateway -> CloudFront: Redirect to Login Page
    CloudFront -> User: HTTPS Response
end
@enduml
